# Usa una imagen ligera de Python
FROM python:3.11-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar solo dependencias primero para aprovechar la caché
COPY requirements.txt .

# Instalar dependencias sin caché para reducir el tamaño de la imagen
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código
COPY . .

# Exponer el puerto en el que corre la API
EXPOSE 5000

# Definir el comando para ejecutar la aplicación
CMD ["gunicorn", "-b", "0.0.0.0:5000", "UpdateUsers:app"]
