name: Build, Push, and Deploy Docker Image listUsers

on:
  push:
    branches:
      - feat/user-management

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAMEJ }}
          password: ${{ secrets.DOCKER_PASSWORDJ }}

      - name: Build listUsers Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAMEJ }}/listusers:latest ./User_management/backend/listUsers

      - name: Push listUsers Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAMEJ }}/listusers:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.EC2_SSH_KEYJ }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Set Environment Variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOSTJ }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USERJ }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORDJ }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAMEJ }}" >> $GITHUB_ENV

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-44-204-238-202.compute-1.amazonaws.com << 'EOF'
            if ! command -v docker &> /dev/null
            then
              sudo dnf install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi
            
            sudo docker pull ${{ secrets.DOCKER_USERNAMEJ }}/listusers:latest
            sudo docker stop listusers || true
            sudo docker rm listusers || true

            # Run the new container with environment variables
            sudo docker run -d --name listusers \
              -p 4567:4567 \
              -e DB_HOST="$DB_HOST" \
              -e DB_USER="$DB_USER" \
              -e DB_PASSWORD="$DB_PASSWORD" \
              -e DB_NAME="$DB_NAME" \
              ${{ secrets.DOCKER_USERNAMEJ }}/listusers:latest
          EOF
