name: Build, Push, and Deploy UserList Microservice

on:
  push:
    branches:
      - feat/user-management
    paths:
      - "user-management/frontend/UserList/**"
      - ".github/workflows/listUsersFr.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAMEJ }}
          password: ${{ secrets.DOCKER_PASSWORDJ }}

      - name: Build UserList-fr Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAMEJ }}/userlist-fr:latest ./User_management/frontend/UserList

      - name: Push UserList-fr Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAMEJ }}/userlist-fr:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.EC2_SSH_KEYJ }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-44-205-135-240.compute-1.amazonaws.com << 'EOF'
            sudo docker stop userlist-fr || true
            sudo docker rm userlist-fr || true

            sudo docker pull ${{ secrets.DOCKER_USERNAMEJ }}/userlist-fr:latest
            sudo docker run -d --name userlist-fr -p 80:5173 ${{ secrets.DOCKER_USERNAMEJ }}/userlist-fr:latest
          EOF
