name: Deploy MongoDB to EC2

on:
  push:
    paths:
      - '.github/workflows/mongo_db.yml'
    branches: [ "test_gestion_producto" ]
  pull_request:
    paths:
      - '.github/workflows/mongo_db.yml'
    branches: 
      - "QA"
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository to the runner
      - name: Retrieve repository
        uses: actions/checkout@v4

      # Step 2: Establish SSH connection and set up MongoDB on EC2
      - name: Configure and deploy MongoDB on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_MONGODB }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo " Successfully connected via SSH"

            # Verify if Docker is installed, install it if missing
            if ! command -v docker &> /dev/null; then
              echo "⚙ Installing Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi

            # Remove any existing MongoDB container to avoid conflicts
            if [ "$(sudo docker ps -aq -f name=mongo_container)" ]; then
              echo "🗑 Removing pre-existing MongoDB container..."
              sudo docker stop mongo_container
              sudo docker rm mongo_container
            fi

            # Deploy a new MongoDB container
            echo " Launching MongoDB instance..."
            sudo docker run -d \
              --name mongo_container \
              -p 27017:27017 \
              -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGODB_USER }} \
              -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGODB_PASSWORD }} \
              -v /home/${{ secrets.EC2_USER }}/mongodb_data:/data/db \
              --restart unless-stopped \
              mongo

            echo " MongoDB deployment completed successfully on EC2"
