name: Build, Push to Docker Hub, and Deploy to EC2

on:
  push:
    paths:
      - "update_service/**"  # Solo ejecuta el workflow si hay cambios en este directorio
    branches: ["test_yml"]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configura el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Inicia sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir la imagen de Docker
      - name: Build Docker image
        run: |
          docker build update_service/. --file update_service/Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/update_service:latest \
          --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
          --build-arg MONGODB_DB=${{ secrets.MONGODB_DB }} \
          --build-arg PORT=${{ secrets.PORT }}

      # 4. Subir la imagen al registro de Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/update_service:latest

      # 5. Desplegar en EC2 (Instalar Docker en EC2 si no está instalado)
      - name: Install Docker on EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST4 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Configuración básica en la instancia
            if ! command -v docker &> /dev/null; then
              echo "==> Installing Docker"
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo usermod -a -G docker ec2-user
            fi

            # Detener y eliminar cualquier contenedor existente
            sudo docker stop update_service || true
            sudo docker rm update_service || true

            # Descargar la nueva imagen desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/update_service:latest

            # Ejecutar el contenedor en el puerto 80
            sudo docker run -d \
              --name update_service \
              -p 80:${{ secrets.PORT4 }} \
              -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
              -e MONGODB_DB=${{ secrets.MONGODB_DB }} \
              -e PORT=${{ secrets.PORT }} \
              ${{ secrets.DOCKER_USERNAME }}/update_service:latest
