name: Build, Push, and Deploy Weather Microservice

on:
  push:
    branches:
      - feat/tools-management
    paths:
      - "tools_management/weather-service/**"
      - ".github/workflows/weather-service.yml"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAMEJ }}
          password: ${{ secrets.DOCKER_PASSWORDJ }}

      - name: Build Weather Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAMEJ }}/weather-service:latest ./tools_management/weather-service

      - name: Push Weather Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAMEJ }}/weather-service:latest

  deploy:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.EC2_SSH_KEYJ }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-34-201-173-189.compute-1.amazonaws.com << 'EOF'
            if ! command -v docker &> /dev/null
            then
              brew install --cask docker
              open /Applications/Docker.app
              sleep 30  # Wait for Docker to start
            fi
            docker pull ${{ secrets.DOCKER_USERNAMEJ }}/weather-service:latest
            docker stop weather-service || true
            docker rm weather-service || true
            docker run -d -p 3009:3018 --name weather-service \
              --env "WEATHER_API_KEY=$(echo '${{ secrets.WEATHER_API_KEYJ }}' | tr -d '\n')" \
              --env "WEATHER_API_URL=$(echo '${{ secrets.WEATHER_API_URLJ }}' | tr -d '\n')" \
              ${{ secrets.DOCKER_USERNAMEJ }}/weather-service:latest
          EOF
