name: Build, Push, and Deploy World Clock Microservice

on:
  push:
    branches:
      - feat/tools-management
    paths:
      - "tools_management/world-clock-service/**"
      - ".github/workflows/world-clock-service.yml"

jobs:
  build:
    runs-on: ubuntu-latest  # Cambiado a ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx manually
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAMEJ }}
          password: ${{ secrets.DOCKER_PASSWORDJ }}

      - name: Build World Clock Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAMEJ }}/world-clock-service:latest ./tools_management/world-clock-service

      - name: Push World Clock Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAMEJ }}/world-clock-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.EC2_SSH_KEYJ }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-34-201-173-189.compute-1.amazonaws.com << 'EOF'
            if ! command -v docker &> /dev/null
            then
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Agregar ec2-user al grupo docker
            sudo usermod -aG docker ec2-user

            # Asegurarse de que docker puede ejecutarse sin sudo
            newgrp docker

            docker pull ${{ secrets.DOCKER_USERNAMEJ }}/world-clock-service:latest
            docker stop world-clock-service || true
            docker rm world-clock-service || true

            docker run -d -p 3010:3019 --name world-clock-service \
              ${{ secrets.DOCKER_USERNAMEJ }}/world-clock-service:latest
          EOF
